/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Nat;
export const PublicUser = IDL.Record({
  'id' : UserId,
  'about' : IDL.Text,
  'username' : IDL.Text,
  'name' : IDL.Text,
  'joinedAt' : IDL.Int,
  'avatarUrl' : IDL.Text,
  'isAdmin' : IDL.Bool,
  'phone' : IDL.Text,
});
export const ConversationInfo = IDL.Record({
  'otherUserName' : IDL.Text,
  'otherUserId' : UserId,
  'lastMessage' : IDL.Text,
  'otherUserAvatar' : IDL.Text,
  'lastTimestamp' : IDL.Int,
  'chatId' : IDL.Text,
  'otherUserUsername' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'imageUrl' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderName' : IDL.Text,
  'chatId' : IDL.Text,
  'senderId' : UserId,
});
export const LoginResult = IDL.Variant({
  'ok' : IDL.Record({ 'token' : IDL.Text, 'user' : PublicUser }),
  'err' : IDL.Text,
});
export const RegisterResult = IDL.Variant({
  'ok' : IDL.Record({ 'token' : IDL.Text, 'userId' : UserId }),
  'err' : IDL.Text,
});
export const OtpResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const HttpResponsePayload = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })),
});
export const TransformArgs = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpResponsePayload,
});

export const idlService = IDL.Service({
  'aanyaReply' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Opt(IDL.Nat)],
      [],
    ),
  'addFriend' : IDL.Func(
      [IDL.Text, UserId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminGetStats' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({ 'users' : IDL.Vec(PublicUser), 'userCount' : IDL.Nat })
        ),
      ],
      [],
    ),
  'areFriends' : IDL.Func([UserId, UserId], [IDL.Bool], ['query']),
  'checkUserExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'forceResetPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getAanyaConversations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ConversationInfo)],
      [],
    ),
  'getAanyaProfile' : IDL.Func([], [IDL.Opt(PublicUser)], ['query']),
  'getAanyaUserId' : IDL.Func([], [IDL.Nat], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(PublicUser)], ['query']),
  'getChatWallpaper' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getMyFriends' : IDL.Func([IDL.Text], [IDL.Vec(PublicUser)], []),
  'getMyProfile' : IDL.Func([IDL.Text], [IDL.Opt(PublicUser)], []),
  'getUserById' : IDL.Func([UserId], [IDL.Opt(PublicUser)], ['query']),
  'getUserByUsername' : IDL.Func([IDL.Text], [IDL.Opt(PublicUser)], ['query']),
  'getUserConversations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ConversationInfo)],
      [],
    ),
  'heartbeat' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'isPhoneRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isSmsConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserOnline' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'isUsernameAvailablePublic' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'loginWithOtp' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'loginWithPassword' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'logout' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [RegisterResult], []),
  'registerWithOtp' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [RegisterResult],
      [],
    ),
  'registerWithPassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [RegisterResult],
      [],
    ),
  'requestOtp' : IDL.Func([IDL.Text], [OtpResult], []),
  'resetAdminPassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'sendAanyaProactive' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(IDL.Nat)], []),
  'sendAanyaWelcome' : IDL.Func([IDL.Nat], [], []),
  'sendMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Nat)],
      [],
    ),
  'sendMessageAsBot' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Opt(IDL.Nat)],
      [],
    ),
  'setApiKey' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'setChatWallpaper' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'setUsername' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'transformHttpResponse' : IDL.Func(
      [TransformArgs],
      [HttpResponsePayload],
      ['query'],
    ),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Nat;
  const PublicUser = IDL.Record({
    'id' : UserId,
    'about' : IDL.Text,
    'username' : IDL.Text,
    'name' : IDL.Text,
    'joinedAt' : IDL.Int,
    'avatarUrl' : IDL.Text,
    'isAdmin' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const ConversationInfo = IDL.Record({
    'otherUserName' : IDL.Text,
    'otherUserId' : UserId,
    'lastMessage' : IDL.Text,
    'otherUserAvatar' : IDL.Text,
    'lastTimestamp' : IDL.Int,
    'chatId' : IDL.Text,
    'otherUserUsername' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'imageUrl' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderName' : IDL.Text,
    'chatId' : IDL.Text,
    'senderId' : UserId,
  });
  const LoginResult = IDL.Variant({
    'ok' : IDL.Record({ 'token' : IDL.Text, 'user' : PublicUser }),
    'err' : IDL.Text,
  });
  const RegisterResult = IDL.Variant({
    'ok' : IDL.Record({ 'token' : IDL.Text, 'userId' : UserId }),
    'err' : IDL.Text,
  });
  const OtpResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const HttpResponsePayload = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })),
  });
  const TransformArgs = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpResponsePayload,
  });
  
  return IDL.Service({
    'aanyaReply' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
    'addFriend' : IDL.Func(
        [IDL.Text, UserId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminGetStats' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({ 'users' : IDL.Vec(PublicUser), 'userCount' : IDL.Nat })
          ),
        ],
        [],
      ),
    'areFriends' : IDL.Func([UserId, UserId], [IDL.Bool], ['query']),
    'checkUserExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'forceResetPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getAanyaConversations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ConversationInfo)],
        [],
      ),
    'getAanyaProfile' : IDL.Func([], [IDL.Opt(PublicUser)], ['query']),
    'getAanyaUserId' : IDL.Func([], [IDL.Nat], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(PublicUser)], ['query']),
    'getChatWallpaper' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getMyFriends' : IDL.Func([IDL.Text], [IDL.Vec(PublicUser)], []),
    'getMyProfile' : IDL.Func([IDL.Text], [IDL.Opt(PublicUser)], []),
    'getUserById' : IDL.Func([UserId], [IDL.Opt(PublicUser)], ['query']),
    'getUserByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PublicUser)],
        ['query'],
      ),
    'getUserConversations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ConversationInfo)],
        [],
      ),
    'heartbeat' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'isPhoneRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isSmsConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserOnline' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'isUsernameAvailablePublic' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'loginWithOtp' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'loginWithPassword' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'logout' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [RegisterResult], []),
    'registerWithOtp' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [RegisterResult],
        [],
      ),
    'registerWithPassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [RegisterResult],
        [],
      ),
    'requestOtp' : IDL.Func([IDL.Text], [OtpResult], []),
    'resetAdminPassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'sendAanyaProactive' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
    'sendAanyaWelcome' : IDL.Func([IDL.Nat], [], []),
    'sendMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
    'sendMessageAsBot' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
    'setApiKey' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'setChatWallpaper' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'setUsername' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'transformHttpResponse' : IDL.Func(
        [TransformArgs],
        [HttpResponsePayload],
        ['query'],
      ),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };