/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConversationInfo {
  'otherUserName' : string,
  'otherUserId' : UserId,
  'lastMessage' : string,
  'otherUserAvatar' : string,
  'lastTimestamp' : bigint,
  'chatId' : string,
  'otherUserUsername' : string,
}
export interface HttpResponsePayload {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<{ 'value' : string, 'name' : string }>,
}
export type LoginResult = { 'ok' : { 'token' : string, 'user' : PublicUser } } |
  { 'err' : string };
export interface Message {
  'id' : bigint,
  'text' : string,
  'imageUrl' : string,
  'timestamp' : bigint,
  'senderName' : string,
  'chatId' : string,
  'senderId' : UserId,
}
export type OtpResult = { 'ok' : string } |
  { 'err' : string };
export interface PublicUser {
  'id' : UserId,
  'about' : string,
  'username' : string,
  'name' : string,
  'joinedAt' : bigint,
  'avatarUrl' : string,
  'isAdmin' : boolean,
  'phone' : string,
}
export type RegisterResult = {
    'ok' : { 'token' : string, 'userId' : UserId }
  } |
  { 'err' : string };
export interface TransformArgs {
  'context' : Uint8Array,
  'response' : HttpResponsePayload,
}
export type UserId = bigint;
export interface _SERVICE {
  'aanyaReply' : ActorMethod<[string, bigint, string], [] | [bigint]>,
  'addFriend' : ActorMethod<
    [string, UserId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminGetStats' : ActorMethod<
    [string],
    [] | [{ 'users' : Array<PublicUser>, 'userCount' : bigint }]
  >,
  'areFriends' : ActorMethod<[UserId, UserId], boolean>,
  'checkUserExists' : ActorMethod<[string], boolean>,
  'forceResetPassword' : ActorMethod<[string, string], string>,
  'getAanyaConversations' : ActorMethod<[string], Array<ConversationInfo>>,
  'getAanyaProfile' : ActorMethod<[], [] | [PublicUser]>,
  'getAanyaUserId' : ActorMethod<[], bigint>,
  'getAllUsers' : ActorMethod<[], Array<PublicUser>>,
  'getChatWallpaper' : ActorMethod<[string], string>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'getMyFriends' : ActorMethod<[string], Array<PublicUser>>,
  'getMyProfile' : ActorMethod<[string], [] | [PublicUser]>,
  'getUserById' : ActorMethod<[UserId], [] | [PublicUser]>,
  'getUserByUsername' : ActorMethod<[string], [] | [PublicUser]>,
  'getUserConversations' : ActorMethod<[string], Array<ConversationInfo>>,
  'heartbeat' : ActorMethod<[string], boolean>,
  'isPhoneRegistered' : ActorMethod<[string], boolean>,
  'isSmsConfigured' : ActorMethod<[], boolean>,
  'isUserOnline' : ActorMethod<[UserId], boolean>,
  'isUsernameAvailablePublic' : ActorMethod<[string], boolean>,
  'login' : ActorMethod<[string, string], LoginResult>,
  'loginWithOtp' : ActorMethod<[string, string], LoginResult>,
  'loginWithPassword' : ActorMethod<[string, string], LoginResult>,
  'logout' : ActorMethod<[string], boolean>,
  'register' : ActorMethod<[string, string, string], RegisterResult>,
  'registerWithOtp' : ActorMethod<
    [string, string, string, string],
    RegisterResult
  >,
  'registerWithPassword' : ActorMethod<
    [string, string, string],
    RegisterResult
  >,
  'requestOtp' : ActorMethod<[string], OtpResult>,
  'resetAdminPassword' : ActorMethod<[string, string, string], string>,
  'sendAanyaProactive' : ActorMethod<[bigint, string], [] | [bigint]>,
  'sendAanyaWelcome' : ActorMethod<[bigint], undefined>,
  'sendMessage' : ActorMethod<[string, string, string, string], [] | [bigint]>,
  'sendMessageAsBot' : ActorMethod<[string, bigint, string], [] | [bigint]>,
  'setApiKey' : ActorMethod<[string, string], boolean>,
  'setChatWallpaper' : ActorMethod<[string, string, string], boolean>,
  'setUsername' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'transformHttpResponse' : ActorMethod<[TransformArgs], HttpResponsePayload>,
  'updateProfile' : ActorMethod<[string, string, string, string], boolean>,
  'verifyOtp' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];