/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = bigint;
export type RegisterResult = {
    __kind__: "ok";
    ok: {
        token: string;
        userId: UserId;
    };
} | {
    __kind__: "err";
    err: string;
};
export interface HttpResponsePayload {
    status: bigint;
    body: Uint8Array;
    headers: Array<{
        value: string;
        name: string;
    }>;
}
export interface ConversationInfo {
    otherUserName: string;
    otherUserId: UserId;
    lastMessage: string;
    otherUserAvatar: string;
    lastTimestamp: bigint;
    chatId: string;
    otherUserUsername: string;
}
export interface Message {
    id: bigint;
    text: string;
    imageUrl: string;
    timestamp: bigint;
    senderName: string;
    chatId: string;
    senderId: UserId;
}
export type LoginResult = {
    __kind__: "ok";
    ok: {
        token: string;
        user: PublicUser;
    };
} | {
    __kind__: "err";
    err: string;
};
export interface PublicUser {
    id: UserId;
    about: string;
    username: string;
    name: string;
    joinedAt: bigint;
    avatarUrl: string;
    isAdmin: boolean;
    phone: string;
}
export type OtpResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface TransformArgs {
    context: Uint8Array;
    response: HttpResponsePayload;
}
export interface backendInterface {
    aanyaReply(adminToken: string, targetUserId: bigint, replyText: string): Promise<bigint | null>;
    addFriend(token: string, friendId: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetStats(token: string): Promise<{
        users: Array<PublicUser>;
        userCount: bigint;
    } | null>;
    areFriends(userId1: UserId, userId2: UserId): Promise<boolean>;
    checkUserExists(uname: string): Promise<boolean>;
    forceResetPassword(targetUsername: string, newPassword: string): Promise<string>;
    getAanyaConversations(adminToken: string): Promise<Array<ConversationInfo>>;
    getAanyaProfile(): Promise<PublicUser | null>;
    getAanyaUserId(): Promise<bigint>;
    getAllUsers(): Promise<Array<PublicUser>>;
    getChatWallpaper(chatId: string): Promise<string>;
    getMessages(chatId: string): Promise<Array<Message>>;
    getMyFriends(token: string): Promise<Array<PublicUser>>;
    getMyProfile(token: string): Promise<PublicUser | null>;
    getUserById(userId: UserId): Promise<PublicUser | null>;
    getUserByUsername(uname: string): Promise<PublicUser | null>;
    getUserConversations(token: string): Promise<Array<ConversationInfo>>;
    heartbeat(token: string): Promise<boolean>;
    isPhoneRegistered(phone: string): Promise<boolean>;
    isSmsConfigured(): Promise<boolean>;
    isUserOnline(userId: UserId): Promise<boolean>;
    isUsernameAvailablePublic(uname: string): Promise<boolean>;
    login(phone: string, pin: string): Promise<LoginResult>;
    loginWithOtp(phone: string, otp: string): Promise<LoginResult>;
    loginWithPassword(username: string, password: string): Promise<LoginResult>;
    logout(token: string): Promise<boolean>;
    register(phone: string, pin: string, name: string): Promise<RegisterResult>;
    registerWithOtp(phone: string, otp: string, name: string, pin: string): Promise<RegisterResult>;
    registerWithPassword(username: string, password: string, name: string): Promise<RegisterResult>;
    requestOtp(phone: string): Promise<OtpResult>;
    resetAdminPassword(targetUsername: string, newPassword: string, recoveryKey: string): Promise<string>;
    sendAanyaProactive(targetUserId: bigint, text: string): Promise<bigint | null>;
    sendAanyaWelcome(newUserId: bigint): Promise<void>;
    sendMessage(token: string, chatId: string, text: string, imageUrl: string): Promise<bigint | null>;
    sendMessageAsBot(adminToken: string, targetUserId: bigint, text: string): Promise<bigint | null>;
    setApiKey(token: string, apiKey: string): Promise<boolean>;
    setChatWallpaper(token: string, chatId: string, wallpaper: string): Promise<boolean>;
    setUsername(token: string, uname: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    transformHttpResponse(args: TransformArgs): Promise<HttpResponsePayload>;
    updateProfile(token: string, name: string, about: string, avatarUrl: string): Promise<boolean>;
    verifyOtp(phone: string, otp: string): Promise<boolean>;
}
import type { LoginResult as _LoginResult, OtpResult as _OtpResult, PublicUser as _PublicUser, RegisterResult as _RegisterResult, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async aanyaReply(arg0: string, arg1: bigint, arg2: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.aanyaReply(arg0, arg1, arg2);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.aanyaReply(arg0, arg1, arg2);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addFriend(arg0: string, arg1: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addFriend(arg0, arg1);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFriend(arg0, arg1);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetStats(arg0: string): Promise<{
        users: Array<PublicUser>;
        userCount: bigint;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetStats(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetStats(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async areFriends(arg0: UserId, arg1: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.areFriends(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.areFriends(arg0, arg1);
            return result;
        }
    }
    async checkUserExists(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkUserExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkUserExists(arg0);
            return result;
        }
    }
    async forceResetPassword(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.forceResetPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.forceResetPassword(arg0, arg1);
            return result;
        }
    }
    async getAanyaConversations(arg0: string): Promise<Array<ConversationInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAanyaConversations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAanyaConversations(arg0);
            return result;
        }
    }
    async getAanyaProfile(): Promise<PublicUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAanyaProfile();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAanyaProfile();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAanyaUserId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAanyaUserId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAanyaUserId();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<PublicUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getChatWallpaper(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatWallpaper(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatWallpaper(arg0);
            return result;
        }
    }
    async getMessages(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getMyFriends(arg0: string): Promise<Array<PublicUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyFriends(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyFriends(arg0);
            return result;
        }
    }
    async getMyProfile(arg0: string): Promise<PublicUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserById(arg0: UserId): Promise<PublicUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserById(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserById(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByUsername(arg0: string): Promise<PublicUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByUsername(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByUsername(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserConversations(arg0: string): Promise<Array<ConversationInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserConversations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserConversations(arg0);
            return result;
        }
    }
    async heartbeat(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.heartbeat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.heartbeat(arg0);
            return result;
        }
    }
    async isPhoneRegistered(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPhoneRegistered(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPhoneRegistered(arg0);
            return result;
        }
    }
    async isSmsConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSmsConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSmsConfigured();
            return result;
        }
    }
    async isUserOnline(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserOnline(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserOnline(arg0);
            return result;
        }
    }
    async isUsernameAvailablePublic(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUsernameAvailablePublic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUsernameAvailablePublic(arg0);
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_LoginResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_LoginResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginWithOtp(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.loginWithOtp(arg0, arg1);
                return from_candid_LoginResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginWithOtp(arg0, arg1);
            return from_candid_LoginResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginWithPassword(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.loginWithPassword(arg0, arg1);
                return from_candid_LoginResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginWithPassword(arg0, arg1);
            return from_candid_LoginResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async register(arg0: string, arg1: string, arg2: string): Promise<RegisterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1, arg2);
                return from_candid_RegisterResult_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1, arg2);
            return from_candid_RegisterResult_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerWithOtp(arg0: string, arg1: string, arg2: string, arg3: string): Promise<RegisterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.registerWithOtp(arg0, arg1, arg2, arg3);
                return from_candid_RegisterResult_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerWithOtp(arg0, arg1, arg2, arg3);
            return from_candid_RegisterResult_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerWithPassword(arg0: string, arg1: string, arg2: string): Promise<RegisterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.registerWithPassword(arg0, arg1, arg2);
                return from_candid_RegisterResult_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerWithPassword(arg0, arg1, arg2);
            return from_candid_RegisterResult_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestOtp(arg0: string): Promise<OtpResult> {
        if (this.processError) {
            try {
                const result = await this.actor.requestOtp(arg0);
                return from_candid_OtpResult_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestOtp(arg0);
            return from_candid_OtpResult_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetAdminPassword(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAdminPassword(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAdminPassword(arg0, arg1, arg2);
            return result;
        }
    }
    async sendAanyaProactive(arg0: bigint, arg1: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.sendAanyaProactive(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendAanyaProactive(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendAanyaWelcome(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendAanyaWelcome(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendAanyaWelcome(arg0);
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2, arg3);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2, arg3);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessageAsBot(arg0: string, arg1: bigint, arg2: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessageAsBot(arg0, arg1, arg2);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessageAsBot(arg0, arg1, arg2);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setApiKey(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setApiKey(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApiKey(arg0, arg1);
            return result;
        }
    }
    async setChatWallpaper(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setChatWallpaper(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setChatWallpaper(arg0, arg1, arg2);
            return result;
        }
    }
    async setUsername(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setUsername(arg0, arg1);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUsername(arg0, arg1);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async transformHttpResponse(arg0: TransformArgs): Promise<HttpResponsePayload> {
        if (this.processError) {
            try {
                const result = await this.actor.transformHttpResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformHttpResponse(arg0);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async verifyOtp(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyOtp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyOtp(arg0, arg1);
            return result;
        }
    }
}
function from_candid_LoginResult_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_OtpResult_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OtpResult): OtpResult {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_RegisterResult_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegisterResult): RegisterResult {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        users: Array<_PublicUser>;
        userCount: bigint;
    }]): {
    users: Array<PublicUser>;
    userCount: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicUser]): PublicUser | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        token: string;
        user: _PublicUser;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        token: string;
        user: PublicUser;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        token: string;
        userId: _UserId;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        token: string;
        userId: UserId;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
